import 'package:flutter/material.dart';

class ColorsTheme {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff03b3c2),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFEFEFE),
    onPrimaryContainer: Color(0xFF011034),
    secondary: Color(0xFFe85963),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE2E4D5),
    onSecondaryContainer: Color(0xFF1A1D14),
    tertiary: Color(0xFF02C9AF),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD5E6E3),
    onTertiaryContainer: Color(0xFF0F1E1C),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFBA1A1A),
    onErrorContainer: Color(0xFFBA1A1A),
    background: Color(0xFFFFFFFF),
    onBackground: Color(0xFF1C1C1A),
    surface: Color(0xFF9d9c9a),
    onSurface: Color(0xFF4b4b4b),
    surfaceVariant: Color(0xFF626461),
    onSurfaceVariant: Color(0xFFEAEEEF),
    outline: Color(0xFFC8C3C9),
    shadow: Color(0xFF000000),
    inverseSurface: Color(0xFF4b4b4b),
    onInverseSurface: Color(0xFFF3F0EC),
    inversePrimary: Color(0xFFBDCCA0),
    surfaceTint: Color(0xFF79A93B),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF02C9AF),
    onPrimary: Color(0xFF9d9c9a),
    primaryContainer: Color(0xFF4b4b4b),
    onPrimaryContainer: Color(0xFFC7C7C0),
    secondary: Color(0xFFe85963),
    onSecondary: Color(0xFF929b9b),
    secondaryContainer: Color(0xFF45483D),
    onSecondaryContainer: Color(0xFFE2E4D5),
    tertiary: Color(0xFF02C9AF),
    onTertiary: Color(0xFF243331),
    tertiaryContainer: Color(0xFF3A4A48),
    onTertiaryContainer: Color(0xFFD5E6E3),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFBA1A1A),
    onErrorContainer: Color(0xFFBA1A1A),
    background: Color(0xFF1C1C1A),
    onBackground: Color(0xFFE5E2DE),
    surface: Color(0xFFC8C3C9),
    onSurface: Color(0xFF4b4b4b),
    surfaceVariant: Color(0xFFEAEEEF),
    onSurfaceVariant: Color(0xFF626461),
    outline: Color(0xFFC8C3C9),
    shadow: Color(0xFF000000),
    inverseSurface: Color(0xFFFEFEFE),
    onInverseSurface: Color(0xFFF3F0EC),
    inversePrimary: Color(0xFFBDCCA0),
    surfaceTint: Color(0xFF79A93B),
  );
}
